version: "3"
services:
  server:
    image: tajpouria/node-tcp-server
    environment:
      - "PORT=7070"
      - "HOST=0.0.0.0"
  nginx:
    image: "nginx:alpine"
    ports:
      - "8080:8080"
    volumes:
      - "./nginx:/etc/nginx"
    links:
      - "server"
