version: '3.4'
services:
  mysql:
    image: mysql:latest
    volumes:
      - ./init.sql:/data/application/init.sql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root

