apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "foo-deployment"
  labels:
    app: "foo"
    tier: "front-end"
spec:
  template:
    metadata:
      name: "foo-pod"
      labels:
        app: "foo"
        tier: "front-end"
    spec:
      containers:
        - name: "nginx"
          image: "nginx:latest"
  replicas: 3
  selector:
    matchLabels:
      app: "foo"
      tier: "front-end"
